# Generated by Django 4.2.23 on 2025-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='poem_media/'),
        ),
        migrations.AddField(
            model_name='poem',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
