# Generated by Django 4.2.23 on 2025-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the document (recommended size: 300x300px)', null=True, upload_to='gallery_thumbnails/'),
        ),
    ]
